# Generated by Django 4.0.6 on 2022-07-07 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_zawodtyperauthor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogabetbets',
            options={'ordering': ['start']},
        ),
        migrations.CreateModel(
            name='ZawodTyperBets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=255)),
                ('pick', models.CharField(max_length=255)),
                ('odd', models.FloatField()),
                ('start', models.DateTimeField(max_length=100)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.zawodtyperauthor')),
                ('dyscipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.dyscipline')),
            ],
            options={
                'ordering': ['start'],
                'abstract': False,
            },
        ),
    ]
