# Generated by Django 4.0.6 on 2022-07-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_alter_blogabetbets_options_zawodtyperbets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumBukmacherskieAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_effective', models.FloatField(null=True)),
                ('author_odds', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='zawodtyperbets',
            name='analise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zawodtyperauthor',
            name='author_effective',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='zawodtyperauthor',
            name='author_odds',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ForumBukmacherskieBets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=255)),
                ('pick', models.CharField(max_length=255)),
                ('odd', models.FloatField()),
                ('start', models.DateTimeField(max_length=100)),
                ('analise', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.forumbukmacherskieauthor')),
                ('dyscipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.dyscipline')),
            ],
            options={
                'ordering': ['start'],
                'abstract': False,
            },
        ),
    ]
