# Generated by Django 4.0.5 on 2022-06-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bet_type', models.CharField(max_length=20)),
                ('bet_amount', models.IntegerField()),
                ('bet_result', models.IntegerField()),
                ('bet_status', models.CharField(max_length=20)),
                ('bet_result_amount', models.IntegerField()),
                ('bet_result_status', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
