# Generated by Django 4.0.5 on 2022-07-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogabetbets',
            name='author_yield',
        ),
        migrations.AlterField(
            model_name='blogabetbets',
            name='stake',
            field=models.IntegerField(),
        ),
    ]
