# Generated by Django 4.0.5 on 2022-07-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_remove_blogabetbets_author_yield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogabetbets',
            name='odd',
            field=models.FloatField(),
        ),
    ]
